import { deepMerge } from '../core/helper';

export default deepMerge(
    // accessibility
    require('./accessibility/forcedColorAdjust').default,

    // backgrounds
    require('./backgrounds/backgroundAttachment').default,
    require('./backgrounds/backgroundClip').default,
    require('./backgrounds/backgroundColor').default,
    require('./backgrounds/backgroundImage').default,
    require('./backgrounds/backgroundOrigin').default,
    require('./backgrounds/backgroundPosition').default,
    require('./backgrounds/backgroundRepeat').default,
    require('./backgrounds/backgroundSize').default,

    // borders
    require('./borders/borderColor').default,
    require('./borders/borderRadius').default,
    require('./borders/borderStyle').default,
    require('./borders/borderWidth').default,
    require('./borders/outlineColor').default,
    require('./borders/outlineOffset').default,
    require('./borders/outlineStyle').default,
    require('./borders/outlineWidth').default,

    // effects
    require('./effects/backgroundBlendMode').default,
    require('./effects/boxShadow').default,
    require('./effects/maskClip').default,
    require('./effects/maskComposite').default,
    require('./effects/maskImage').default,
    require('./effects/maskMode').default,
    require('./effects/maskOrigin').default,
    require('./effects/maskPosition').default,
    require('./effects/maskRepeat').default,
    require('./effects/maskSize').default,
    require('./effects/maskType').default,
    require('./effects/mixBlendMode').default,
    require('./effects/opacity').default,
    require('./effects/textShadow').default,

    // filters
    require('./filters/backdropFilter/blur').default,
    require('./filters/backdropFilter/brightness').default,
    require('./filters/backdropFilter/contrast').default,
    require('./filters/backdropFilter/grayscale').default,
    require('./filters/backdropFilter/hueRotate').default,
    require('./filters/backdropFilter/invert').default,
    require('./filters/backdropFilter/opacity').default,
    require('./filters/backdropFilter/saturate').default,
    require('./filters/backdropFilter/sepia').default,

    // filters
    require('./filters/filter/blur').default,
    require('./filters/filter/brightness').default,
    require('./filters/filter/contrast').default,
    require('./filters/filter/dropShadow').default,
    require('./filters/filter/grayscale').default,
    require('./filters/filter/hueRotate').default,
    require('./filters/filter/invert').default,
    require('./filters/filter/saturate').default,
    require('./filters/filter/sepia').default,

    // grid
    require('./grid/alignContent').default,
    require('./grid/alignItems').default,
    require('./grid/alignSelf').default,
    require('./grid/flex').default,
    require('./grid/flexBasis').default,
    require('./grid/flexDirection').default,
    require('./grid/flexGrow').default,
    require('./grid/flexShrink').default,
    require('./grid/flexWrap').default,
    require('./grid/gap').default,
    require('./grid/gridAutoColumns').default,
    require('./grid/gridAutoFlow').default,
    require('./grid/gridAutoRows').default,
    require('./grid/gridColumn').default,
    require('./grid/gridRow').default,
    require('./grid/gridTemplateColumns').default,
    require('./grid/gridTemplateRows').default,
    require('./grid/justifyContent').default,
    require('./grid/justifyItems').default,
    require('./grid/justifySelf').default,
    require('./grid/order').default,
    require('./grid/placeContent').default,
    require('./grid/placeItems').default,
    require('./grid/placeSelf').default,

    // interactivity
    require('./interactivity/accentColor').default,
    require('./interactivity/appearance').default,
    require('./interactivity/caretColor').default,
    require('./interactivity/colorScheme').default,
    require('./interactivity/cursor').default,
    require('./interactivity/fieldSizing').default,
    require('./interactivity/pointerEvents').default,
    require('./interactivity/resize').default,
    require('./interactivity/scrollBehavior').default,
    require('./interactivity/scrollMargin').default,
    require('./interactivity/scrollPadding').default,
    require('./interactivity/scrollSnapAlign').default,
    require('./interactivity/scrollSnapStop').default,
    require('./interactivity/scrollSnapType').default,
    require('./interactivity/selectNone').default,
    require('./interactivity/touchAction').default,
    require('./interactivity/willChange').default,

    // layout
    require('./layout/aspectRatio').default,
    require('./layout/boxDecorationBreak').default,
    require('./layout/boxSizing').default,
    require('./layout/breakAfter').default,
    require('./layout/breakBefore').default,
    require('./layout/breakInside').default,
    require('./layout/clear').default,
    require('./layout/columns').default,
    require('./layout/display').default,
    require('./layout/float').default,
    require('./layout/isolation').default,
    require('./layout/objectFit').default,
    require('./layout/objectPosition').default,
    require('./layout/overflow').default,
    require('./layout/overscrollBehavior').default,
    require('./layout/position').default,
    require('./layout/topRightBottomLeft').default,
    require('./layout/visibility').default,
    require('./layout/zIndex').default,

    // sizing
    require('./sizing/height').default,
    require('./sizing/maxHeight').default,
    require('./sizing/maxWidth').default,
    require('./sizing/minHeight').default,
    require('./sizing/minWidth').default,
    require('./sizing/width').default,

    // spacing
    require('./spacing/margin').default,
    require('./spacing/padding').default,

    // svg
    require('./svg/fill').default,
    require('./svg/stroke').default,
    require('./svg/strokeWidth').default,

    // tables
    require('./tables/borderCollapse').default,
    require('./tables/borderSpacing').default,
    require('./tables/captionSide').default,
    require('./tables/tableLayout').default,

    // transforms
    require('./transforms/backfaceVisibility').default,
    require('./transforms/perspective').default,
    require('./transforms/perspectiveOrigin').default,
    require('./transforms/rotate').default,
    require('./transforms/scale').default,
    require('./transforms/skew').default,
    require('./transforms/transform').default,
    require('./transforms/transformOrigin').default,
    require('./transforms/transformStyle').default,
    require('./transforms/translate').default,

    // transitions
    require('./transitions/animation').default,
    require('./transitions/transitionBehavior').default,
    require('./transitions/transitionDelay').default,
    require('./transitions/transitionDuration').default,
    require('./transitions/transitionProperty').default,
    require('./transitions/transitionTimingFunction').default,

    // typography
    require('./typography/color').default,
    require('./typography/content').default,
    require('./typography/fontFamily').default,
    require('./typography/fontSize').default,
    require('./typography/fontSmoothing').default,
    require('./typography/fontStretch').default,
    require('./typography/fontStyle').default,
    require('./typography/fontVariantNumeric').default,
    require('./typography/fontWeight').default,
    require('./typography/hyphens').default,
    require('./typography/letterSpacing').default,
    require('./typography/lineClamp').default,
    require('./typography/lineHeight').default,
    require('./typography/listStyleImage').default,
    require('./typography/listStylePosition').default,
    require('./typography/listStyleType').default,
    require('./typography/overflowWrap').default,
    require('./typography/textAlign').default,
    require('./typography/textDecorationColor').default,
    require('./typography/textDecorationLine').default,
    require('./typography/textDecorationStyle').default,
    require('./typography/textDecorationThickness').default,
    require('./typography/textIndent').default,
    require('./typography/textOverflow').default,
    require('./typography/textTransform').default,
    require('./typography/textUnderlineOffset').default,
    require('./typography/textWrap').default,
    require('./typography/verticalAlign').default,
    require('./typography/whiteSpace').default,
    require('./typography/wordBreak').default,
) satisfies GlobalStylesType;
