name: publish to NPM
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'
            - name: publish @codemonster-ru-skincss
              continue-on-error: true
              working-directory: ./packages/@codemonster-ru-skincss
              run: |
                  npm cache clear --force
                  npm ci
                  npm run build
                  npm audit signatures
                  npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: publish @codemonster-ru-vite
              continue-on-error: true
              working-directory: ./packages/@codemonster-ru-vite
              run: |
                  npm cache clear --force
                  npm ci
                  npm run build
                  npm audit signatures
                  npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
